

```{r}
setwd("ALL CSV FILEs")
data=read.csv("Hotel Reservations.csv",stringsAsFactors = T)
```


```{r}
dim(data)
sum(is.na(data))
```

```{r}
summary(data)
```


```{r}
hist(data$required_car_parking_space,col = c("yellowgreen", "yellow"))
hist(data$arrival_year,col = c("skyblue", "pink"))
hist(data$arrival_date, col = c("skyblue",  "pink"))

hist(data$no_of_previous_cancellations, col = c("skyblue",  "red"))
hist(data$no_of_previous_bookings_not_canceled, col = c("skyblue",  "red"))
hist(data$repeated_guest, col = c("yellowgreen",  "skyblue"))
```



```{r}
data1=data[,-c(1,7,10,12,14,15,16)]
head(data1)
```


```{r}
month_name= c("Jan","Feb","Mar","Apr","May", "June","July","Aug","Sep","Oct","Nov","Dec")
data1$arrival_month=factor(data1$arrival_month,levels = 1:12,labels = month_name)
summary(data1)
```


```{r}
library(ggplot2)
library(gridExtra)
```



```{r}
countplot <- ggplot(data1, aes(x = no_of_adults, fill = booking_status)) +
  geom_bar(position="dodge") +
  labs(x = "", y = "", fill = "Booking Status") +
  geom_text(stat='count', aes(label=after_stat(count)),position=position_dodge(width = 0.85), vjust=-0.2) +
  theme(legend.position = c(0.98, 0.98),
        legend.justification = c(1, 1))
grid.arrange(countplot, ncol = 2, widths = c(2, 1),top="Distribution of adults by Cancellation Status")
```


```{r}
child_fre=table(data1$no_of_children)
text(x=barplot(child_fre,col=rainbow(length(child_fre)),xlab = " No of Children",ylab="No of bookings"),y=child_fre,label=child_fre,pos = 3, cex = 0.8)
title(main="Distribution of Number of Children ")


```



```{r}
wknd_fre=table(data1$no_of_weekend_nights)
text(x=barplot(wknd_fre,col=rainbow(length(wknd_fre)),xlab = " No of Weekend Nights",ylab="No of bookings"),y=wknd_fre,label=wknd_fre,pos = 3, cex = 0.8)
title(main = "Distribution of Weekend nights")

```






```{r}
w_fre=table(data1$no_of_week_nights)
text(x=barplot(w_fre,col=rainbow(length(w_fre)),xlab = " No of Week Nights",ylab="No of bookings"),y=w_fre,label=w_fre,pos = 3, cex = 0.5)
title(main = "Distribution of Week Nights")
```






